main: me.mattyhd0.koth.KoTHPlugin
name: KoTH
api-version: 1.13
version: 2.0.7
# Fixed ScheduleManager

description: 'The free solution for servers with King of the Hill'
author: MattyHD0
softdepend: [ PlaceholderAPI ]
load: POSTWORLD
commands:
  koth:
    description: Koth main command
    usage: /<command>